<?php
view('layouts.header', ['title' => 'Audit Reports']);
view('layouts.sidebar');
view('layouts.navbar', ['title' => 'Datacenter Compliance & Audit Reports']);
?>

<div class="card">
    <div class="card-header">
        <div class="card-title">
            <i class="fa-solid fa-file-contract"></i> Generated Audit Reports
        </div>
    </div>

    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Report ID</th>
                    <th>Inspection Code</th>
                    <th>Inspection Title</th>
                    <th>Status</th>
                    <th>Score</th>
                    <th>Generated By</th>
                    <th>Generated Date</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php if (empty($reports)): ?>
                    <tr><td colspan="8" style="text-align:center; color:var(--text-dim);">No generated reports found yet. Complete an inspection to generate a report.</td></tr>
                <?php else: ?>
                    <?php foreach ($reports as $r): ?>
                    <tr>
                        <td>#<?= $r['id'] ?></td>
                        <td><span class="code-text" style="color:var(--accent-cyan); font-weight:600;"><?= sanitize($r['reference_code']) ?></span></td>
                        <td><strong><?= sanitize($r['inspection_title']) ?></strong></td>
                        <td><?= status_badge($r['inspection_status'] ?? 'completed', 'Inspection Statuses') ?></td>
                        <td>
                            <span class="badge badge-<?= $r['score'] >= 90 ? 'success' : ($r['score'] >= 70 ? 'warning' : 'danger') ?>">
                                <?= number_format($r['score'], 1) ?>%
                            </span>
                        </td>
                        <td><?= sanitize($r['generated_by_name']) ?></td>
                        <td><?= sanitize($r['created_at']) ?></td>
                        <td>
                            <a href="/reports/show?id=<?= $r['id'] ?>" class="btn btn-secondary btn-sm"><i class="fa-solid fa-eye"></i> View Summary</a>
                            <a href="/reports/show?id=<?= $r['id'] ?>&print=1" target="_blank" class="btn btn-primary btn-sm"><i class="fa-solid fa-print"></i> Printable PDF</a>
                            <a href="/reports/show?id=<?= $r['id'] ?>&download=1" class="btn btn-success btn-sm"><i class="fa-solid fa-download"></i> Download PDF</a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<?php view('layouts.footer'); ?>
