<?php
view('layouts.header', ['title' => 'Report Summary']);
view('layouts.sidebar');
view('layouts.navbar', ['title' => 'Report Details: #' . $report['id']]);
?>

<div class="card">
    <div class="card-header">
        <div>
            <h2 style="color:#fff; font-size:1.3rem;"><?= sanitize($inspection['title']) ?></h2>
            <p style="color:var(--primary); font-size:0.88rem; margin-top:4px;">Reference: <span class="code-text" style="color:var(--accent-cyan);"><?= sanitize($inspection['reference_code']) ?></span></p>
        </div>
        <div style="display:flex; gap:10px; flex-wrap:wrap;">
            <button type="button" class="btn btn-primary" onclick="openEmailReportModal(event)"><i class="fa-solid fa-paper-plane"></i> Send by Mail</button>
            <a href="/reports/show?id=<?= $report['id'] ?>&download=1" class="btn btn-success"><i class="fa-solid fa-download"></i> Download PDF</a>
            <a href="/reports/show?id=<?= $report['id'] ?>&print=1" target="_blank" class="btn btn-primary"><i class="fa-solid fa-print"></i> Printable View</a>
            <a href="/reports" class="btn btn-secondary"><i class="fa-solid fa-arrow-left"></i> Back to Reports</a>
        </div>
    </div>

    <div style="background:var(--bg-card); padding:20px; border-radius:var(--radius-md); margin-bottom:24px; border:1px solid var(--border-color);">
        <h4 style="color:var(--primary); margin-bottom:8px;">Executive Summary</h4>
        <p style="color:var(--text-muted); font-size:0.92rem;"><?= sanitize($report['summary']) ?></p>
        <div style="margin-top:16px; display:flex; gap:24px; align-items:center; flex-wrap:wrap;">
            <div><strong>Status:</strong> <?= status_badge($inspection['status'] ?? $report['inspection_status'] ?? 'completed', 'Inspection Statuses') ?></div>
            <div><strong>Score:</strong> <span class="badge badge-success"><?= number_format($report['score'], 2) ?>%</span></div>
            <div><strong>Generated By:</strong> <?= sanitize($report['generated_by_name']) ?></div>
            <div><strong>Date:</strong> <?= sanitize($report['created_at']) ?></div>
        </div>
    </div>

    <h3 style="color:#fff; font-size:1.1rem; margin-bottom:16px;"><i class="fa-solid fa-list-check" style="color:var(--accent-cyan);"></i> Checklist Evaluation Breakdown</h3>

    <div class="table-responsive">
        <table class="table" >
            <thead>
                <tr >
                    <th style="color:var(--primary)">Checklist Item</th>
                    <th style="color:var(--primary)">Result Status</th>
                    <th style="color:var(--primary)">Notes & Remarks</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($results as $res): ?>
                <tr style="color:var(--primary)">
                    <td><strong><?= sanitize($res['item_title']) ?></strong></td>
                    <td><?= status_badge($res['result_status'] ?? $res['status'] ?? 'pass', 'Checklist Results') ?></td>
                    <td><?= sanitize($res['notes'] ?? '-') ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
       
    </div>
</div>

<?php
$mailService = new \App\Services\MailService();
$mailSettings = $mailService->getSettings();
$defaultRecipients = !empty($mailSettings['default_recipients']) ? $mailSettings['default_recipients'] : '';
?>
<!-- ========================================================================= -->
<!-- MODAL: SEND REPORT BY EMAIL -->
<!-- ========================================================================= -->
<div id="emailReportModal" class="modal-backdrop" style="display:none; position:fixed; top:0; left:0; width:100vw; height:100vh; background:rgba(15, 23, 42, 0.7); backdrop-filter:blur(4px); z-index:99999; align-items:center; justify-content:center;">
    <div class="modal-dialog" style="max-width:540px; width:92%; margin:auto; background:#ffffff !important; border-radius:var(--radius-lg); overflow:hidden; box-shadow:0 25px 50px -12px rgba(0,0,0,0.5); border:1px solid #cbd5e1; z-index:100000;">
        <div class="modal-content" style="background:#ffffff !important;">
            <div class="modal-header" style="background:#ffffff !important; padding:18px 24px; border-bottom:1px solid var(--border-color); display:flex; justify-content:space-between; align-items:center;">
                <div class="modal-title" style="font-size:1.05rem; font-weight:700; color:var(--text-primary);">
                    <i class="fa-solid fa-paper-plane" style="color:var(--primary);"></i> Send Inspection Report by Email
                </div>
                <button type="button" class="modal-close-btn" onclick="closeEmailReportModal()" style="background:none; border:none; font-size:1.4rem; color:var(--text-secondary); cursor:pointer;">&times;</button>
            </div>
            <form action="/reports/email" method="POST" onsubmit="return handleEmailSend(this, 'btnSendReportEmail')">
                <?= csrf_field() ?>
                <input type="hidden" name="report_id" value="<?= $report['id'] ?>">

                <div class="modal-body" style="background:#ffffff !important; padding:24px; display:flex; flex-direction:column; gap:16px;">
                    <div style="background:#f1f5f9; border:1px solid var(--border-color); border-radius:6px; padding:12px 16px; font-size:0.85rem; color:var(--text-secondary);">
                        Report: <strong style="color:var(--text-primary);"><?= sanitize($inspection['title']) ?></strong> &bull; Reference: <strong style="color:var(--primary);"><?= sanitize($inspection['reference_code']) ?></strong>
                    </div>

                    <div class="form-group">
                        <label class="form-label" style="font-weight:600; font-size:0.86rem; color:var(--text-primary);">Recipient Email(s) <span style="color:var(--color-danger);">*</span></label>
                        <input type="text" name="recipients" class="form-control" placeholder="operations@datacenter.local, manager@company.com" value="<?= sanitize($defaultRecipients) ?>" style="background:#ffffff; color:var(--text-primary); border:1px solid #cbd5e1;" required>
                        <small style="font-size:0.75rem; color:var(--text-secondary); margin-top:4px;">Separate multiple emails with commas.</small>
                    </div>

                    <div class="form-group">
                        <label class="form-label" style="font-weight:600; font-size:0.86rem; color:var(--text-primary);">Custom Message / Notes (Optional)</label>
                        <textarea name="notes" class="form-control" rows="3" placeholder="Add an optional message to accompany the attached PDF report..." style="background:#ffffff; color:var(--text-primary); border:1px solid #cbd5e1;"></textarea>
                    </div>

                    <div class="form-group" style="margin-bottom:0;">
                        <label style="display:flex; align-items:center; gap:8px; cursor:pointer; font-size:0.86rem; font-weight:600; color:var(--text-primary);">
                            <input type="checkbox" name="attach_pdf" value="1" checked style="accent-color:var(--primary); width:16px; height:16px;">
                            Attach Official PDF Compliance Report
                        </label>
                    </div>
                </div>

                <div class="modal-footer" style="background:#f8fafc !important; padding:16px 24px; border-top:1px solid var(--border-color); display:flex; justify-content:flex-end; gap:12px;">
                    <button type="button" class="btn btn-secondary" onclick="closeEmailReportModal()">Cancel</button>
                    <button type="submit" id="btnSendReportEmail" class="btn btn-primary">
                        <i class="fa-solid fa-paper-plane"></i> Send Email
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
function openEmailReportModal(e) {
    if (e && typeof e.stopPropagation === 'function') e.stopPropagation();
    const m = document.getElementById('emailReportModal');
    if (m) {
        m.style.setProperty('display', 'flex', 'important');
    }
}
function closeEmailReportModal() {
    const m = document.getElementById('emailReportModal');
    if (m) {
        m.style.setProperty('display', 'none', 'important');
    }
}
function handleEmailSend(form, btnId) {
    const btn = document.getElementById(btnId);
    if (btn) {
        btn.disabled = true;
        btn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Sending Email...';
    }
    return true;
}
window.addEventListener('click', (e) => {
    const m = document.getElementById('emailReportModal');
    if (e.target === m) closeEmailReportModal();
});
</script>

<?php view('layouts.footer'); ?>
